apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: jvm-build-suite-component-gqud
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jvm-build-suite-component-gqud
    app.kubernetes.io/part-of: jvm-build-suite-application-aqdm
  name: jvm-build-suite-component-gqud
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: jvm-build-suite-component-gqud
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: jvm-build-suite-component-gqud
    spec:
      containers:
      - image: quay.io/qijing/jvm-build-ntsz-tenant/jvm-build-suite-application-aqdm/jvm-build-suite-component-gqud@sha256:dda58cbeb74b1e7c87dc1e094a4d0fe034304b1f8ecb6523b16f102962a2459b
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
