apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: jvm-build-suite-component-gqud
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/qijing/jvm-build-ntsz-tenant/jvm-build-suite-application-aqdm/jvm-build-suite-component-gqud@sha256:dda58cbeb74b1e7c87dc1e094a4d0fe034304b1f8ecb6523b16f102962a2459b
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
